### ISSUE TITLE
not_authed error when credentials are passed in

### ISSUE THREAD

**Issue by brandoncurtis** [Askia/askia-slack-poll#1]
I'm launching the application like this:
```
export SLACK_APP_OAUTH=xoxp-myoauth
export SLACK_APP_TOKEN=myapptoken
export PORT=443
export SSL_KEY=/path/to/privkey.pem
export SSL_CERT=/path/to/cert.pem
export SSL_CHAIN=/path/to/chain.pem
export SLACK_CLIENT_ID=myid
export SLACK_CLIENT_SECRET=mysecret
node index.js
```

and I'm receiving this error in the terminal when I attempt to run the slash command in Slack:
```
{ Error: An API error occurred: not_authed
    at Object.platformErrorFromResult (/root/repos/askia-slack-poll/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/root/repos/askia-slack-poll/node_modules/@slack/web-api/dist/WebClient.js:374:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'slack_webapi_platform_error',
  data:
   { ok: false,
     error: 'not_authed',
     response_metadata: { acceptedScopes: [Array] } } }
```
Am I missing something?

**Comment by ysaskia** [comment]
Hi @brandoncurtis. Thank you for your report. 
Sadly I'm very busy actually and will not have time to look into it before next week (I hope).
Will keep you updated as soon I can get some times :)

**Comment by ysaskia** [comment]
@brandoncurtis I will need to know the context of the command. 
1. If your app was installed with slack button or not. 
2. If it was a DM (direct message) a private group, public channel, etc.

**Comment by ysaskia** [comment]
After some investigations there was multiple issues (Only for DM or private group): 

One of these issues was on the project and is now fixed. I suggest you to clear your `teams` collection in mongo and reinstall the app again.

Other issues are related to slack. In fact when using poll in DM. It needs to be installed by the user which send the poll. Another issue happens when multiple install made by the same user can invalidate the app or some functionality for this user or both.

**Comment by brandoncurtis** [comment]
I'm running this on a droplet in Digital Ocean.  My app was not installed with the Slack button; I haven't configured the app's Redirect URLs because it didn't look like I needed to if I wasn't going to distribute it.  I'm attempting to start the poll in a public channel with the same user that created the app.

I've updated to the newest version and now the error reads:
```
{ Error: An API error occurred: invalid_auth
    at Object.platformErrorFromResult (/root/repos/askia-slack-poll/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/root/repos/askia-slack-poll/node_modules/@slack/web-api/dist/WebClient.js:374:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'invalid_auth', response_metadata: {} } }
```

The README should probably indicate that mongodb is a dependency, and the app should indicate when that dependency has not been met.

**Comment by ysaskia** [comment]
Hey! 

The app has been made to be distributed. So every actions needs to be authed which means that the app install is required. Anyway, I just pushed a quick solution to be able to run the app without the team authentication. This is not tested since I don't have the time to deploy another server with your setup. So I will wait for your  feebback. After pulling the code and before restart the app, you'll have to set a new env var `DISABLE_SLACK_TEAM_AUTH` to any value.

**Comment by ysaskia** [comment]
Finally I have been able to test it and after a few tries the application will not support not authed actions since it can easily work in safe mode even for not distributed app. So the change will be reverted. Anyway, to proceed in your slack app manager go to `oauth & permissions` and be sure to configure your redirect url to `https://{yourserveraddress}/slack/auth/redirect` when done go to `manage distribution` and click on the slack button to proceed to the installation.

**Comment by ysaskia** [comment]
Steps added to the `Readme.md`
